### ISSUE TITLE
Resolve CSRF token error in prod

### ISSUE THREAD

**Issue by enoren5** [enoren5/tarot_juicer#109]
Django throws CSRF 403 Forbidden intermittently. It’s difficult to reproduce every time. It only happens in production, never locally while testing. This issue requires:
1. An answer to explain: Why is this happening?
2. Ensure that it doesn’t happen going forward

**Comment by umar-arq** [comment]
@enoren5 that can be happened due to some reasons like:

- When we didn't run migrations
- When there is an empty object came or an empty request is recieved
- When exception handling is not implemented

We can minimise it by creating some test case, like how users will be interacting to website, which options they will use, So we can prevent it easily, We can also add a wrapper like a try and catch block to prevent it. We will implement the best method you prefer 😍

@enoren5 brother, thank you

**Comment by enoren5** [comment]
> We can also add a wrapper like a try and catch block to prevent it. 

I'll go with this option.

**Comment by umar-arq** [comment]
> > We can also add a wrapper like a try and catch block to prevent it.
> 
> I'll go with this option.
> 
> @umar-arq

Okay @enoren5 brother 🥳✌️👌🤩❤️😇

**Comment by enoren5** [comment]
Based on my one on one conversation with Umar on Upwork on June 20th, 2021, he shared a video demonstrating two scenarios where a CSRF 403 Forbidden error is triggered. Umar also referred to Django's official support docs. I will explore these and start a thread on the Django forums if necessary at my next opportunity. Thanks, @umar-arq!
