### ISSUE TITLE
Google Analytics:  GA4 / Universal Analytics questions about implementation and template fixes

### ISSUE THREAD

**Issue by enoren5** [enoren5/tarot_juicer#161]
Which version of Google Analytics is already implemented on my site? Is it `GA4`? Or is it the former deprecated `Universal Analytics` platform? If it is a Universal Analytics platform, your task is to upgrade every template to GA4. However if GA4 is already implemented, then your task is to resolve the potential conflict described below.

Google Analytics was a new feature we originally described in Issue #123 and implemented in PR #129. At the time when I merged #129 into `master`, there was a merge conflict with two separate Google Analytics Javascript code snippets:
- The old legacy/deprecated one
- The new one
There still may be a conflict but I am not sure. 

For example, `gateway.html` and the `base.html` partial include one Google Analytics site tag:
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-1KHJ7HMKT1"></script>
<script>

 window.dataLayer = window.dataLayer || [];
 function gtag() { dataLayer.push(arguments); }
 gtag('js', new Date());

 gtag('config', 'G-1KHJ7HMKT1');
</script>
<!-- GOOGLE ANALYTICS -->
```
First question: Is the above the only Google Analytics code required?

In addition to the above Google Analytics JavaScript, the `portal.html` template includes two more. They look like this: 
```
 <!-- Google Tag Manager -->
 <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-T3WKDW" height="0" width="0"
   style="display:none;visibility:hidden"></iframe></noscript>
<script>(function (w, d, s, l, i) {
   w[l] = w[l] || []; w[l].push({
     'gtm.start':
       new Date().getTime(), event: 'gtm.js'
   }); var f = d.getElementsByTagName(s)[0],
     j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
       '//www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
 })(window, document, 'script', 'dataLayer', 'GTM-T3WKDW');</script>
<!-- End Google Tag Manager -->

```
And:
```
 <script>
    document.addEventListener("DOMContentLoaded", function () {
      const introText = document.getElementsByClassName('intro__text'),
        introBtn = document.getElementsByClassName('intro__btn');

      introBtn[0].addEventListener('click', () => alert('Hello World!'));

      setTimeout(() => {
        introText[0].classList.add('start');
        introBtn[0].classList.add('start');
      }, 800);
    });

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-XXXXXXXX-Y']);
    _gaq.push(['_trackPageview']);
    (function () {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
```
Second question: Are all three required? Or can we eliminate these two outdated ones?

Third question: If I add the Google site tag quoted initially above to my new custom 500 and 404 template, will that be enough for Google Analytics to begin tracking page views and all the other data?

**Comment by abubakarA-Dot** [comment]
We only need to keep google analytics and google tag manager to track the page views and we don't need Universal Analytics which is deprecated and will be eliminated from 2023. so I am removing UA code and will be keeping only google analytics code( it is the latest code supported by Google itself) and google tag managers to send the event data to google analytics.
answer to your first question:
Yes, We need to keep the Google Analytics code in your website templates. It is a must kind of code to keep on your website to start tracking user views.
Answer to your Question 2:
I have found something from official google analytics about google tag managers or gtag.js which is given below:
""" The global site tag (gtag.js) is a JavaScript tagging framework and API that allows you to send event data to Google Analytics, Google Ads, and Google Marketing Platform."""
so it means we also need to keep the GTM API code snippet so that it can send event data to google analytics to track the user views.
Answer to your question 3:
Yes, It will be enough to track the page views by just adding google analytics code snippet(Quoted code).

**Comment by enoren5** [comment]
@abubakarA-Dot's fully answered the three questions in the original post. Deprecated UA code snippets purged from `portal.html` template in PR #194. Closing as Reoslved.

**Comment by enoren5** [comment]
Thanks Abu!
